/*
 *  Copyright (C) 2011 Prem Sasidharan.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * published by the Free Software Foundation.
*/

#include <video_widget.h>

const char Video_widget::shader_program[] =
"uniform int mode;\n"
"uniform int views;\n"
"uniform int format_1;\n"
"uniform int format_2;\n"
"uniform int stereo_mode;\n"
"uniform sampler2D texture_0;\n"
"uniform sampler2D texture_1;\n"
"uniform sampler2D texture_2;\n"
"uniform sampler2D texture_3;\n"
"uniform sampler2D texture_4;\n"
"uniform sampler2D texture_5;\n"
"void extract_yuv(in int format, in sampler2D texture0, in sampler2D texture1, in sampler2D texture2, out float y, out float u, out float v)\n"
"{\n"
"    y = 0.0; u = 0.0; v = 0.0;\n"
"    if (format == 1) {\n"
"        y = texture2D(texture0, gl_TexCoord[0].st).r;\n"
"        y = 1.1643 * (y - 0.0625);\n"
"        u = texture2D(texture1, gl_TexCoord[0].st).r - 0.5;\n"
"        v = texture2D(texture2, gl_TexCoord[0].st).r - 0.5;\n"
"    } else if (format == 2) {\n"
"        y = texture2D(texture0, gl_TexCoord[0].st).r;\n"
"        y = 1.1643*(y-0.0625);\n"
"        u = texture2D(texture1, gl_TexCoord[0].st).g-0.5;\n"
"        v = texture2D(texture1, gl_TexCoord[0].st).a-0.5;\n"
"    } else if (format == 3) {\n"
"        y = texture2D(texture0, gl_TexCoord[0].st).g;\n"
"        y = 1.1643*(y-0.0625);\n"
"        u = texture2D(texture1, gl_TexCoord[0].st).r-0.5;\n"
"        v = texture2D(texture1, gl_TexCoord[0].st).b-0.5;\n"
"    }\n"
"}\n"
"void convert_to_rgb(in float y, in float u, in float v, out float r, out float g, out float b)\n"
"{\n"
"    if (mode == 0) {\n"
"        r = y; g = y; b = y;\n"
"    } else if (mode == 1) {\n"
"        r = u; g = u; b = u;\n"
"    } else if (mode == 2) {\n"
"        r = v; g = v; b = v;\n"
"    } else {\n"
"       r = y+1.5958*v;\n"
"       g = y-0.39173*u-0.81290*v;\n"
"       b = y+2.017*u;\n"	
"		if (mode == 3) {\n"
"           g = 0.0; b = 0.0;\n"
"       } else if (mode == 4) {\n"
"           r = 0.0; b = 0.0;\n"
"       } else if (mode == 5) {\n"
"           r = 0.0; g = 0.0;\n"
"       }\n"
"    }\n"
"}\n"
"void main(void)\n"
"{\n"
"    float y1, u1, v1;\n"
"    float r1 = 0.0, g1 = 0.0, b1 = 0.0;\n"
"    extract_yuv(format_1, texture_0, texture_1, texture_2, y1, u1, v1);\n"
"    convert_to_rgb(y1, u1, v1, r1, g1, b1);\n"
"    if (views == 1)\n"
"        gl_FragColor = vec4(r1, g1, b1, 1.0);\n"
"    else {\n"
"        float y2, u2, v2;\n"
"        float r2 = 0.0, g2 = 0.0, b2 = 0.0;\n"
"        extract_yuv(format_2, texture_3, texture_4, texture_5, y2, u2, v2);\n"
"        convert_to_rgb(y2, u2, v2, r2, g2, b2);\n"
"        if (stereo_mode == 1) {\n"
"           gl_FragColor = vec4(r1, g1, b1, 1.0);\n"
"        } else if (stereo_mode == 2) {\n"
"           gl_FragColor = vec4(r2, g2, b2, 1.0);\n"
"        } else if (stereo_mode == 3) {\n"
"           if (gl_TexCoord[0].x > 0.5) {\n"
"               gl_FragColor = vec4(r1, g1, b1, 1.0);\n"
"           } else {\n"
"               gl_FragColor = vec4(r2, g2, b2, 1.0);\n"
"           }\n"
"        } else if (stereo_mode == 4) {\n"
"           if (gl_TexCoord[0].y > 0.5) {\n"
"               gl_FragColor = vec4(r1, g1, b1, 1.0);\n"
"           } else {\n"
"               gl_FragColor = vec4(r2, g2, b2, 1.0);\n"
"           }\n"
"        } else if (stereo_mode == 5) {\n"
"           if (gl_TexCoord[0].x > gl_TexCoord[0].y) {\n"
"               gl_FragColor = vec4(r1, g1, b1, 1.0);\n"
"           } else {\n"
"               gl_FragColor = vec4(r2, g2, b2, 1.0);\n"
"           }\n"
"        } else if (stereo_mode == 6) {\n"
"           if (gl_TexCoord[0].x < gl_TexCoord[0].y) {\n"
"               gl_FragColor = vec4(r1, g1, b1, 1.0);\n"
"           } else {\n"
"               gl_FragColor = vec4(r2, g2, b2, 1.0);\n"
"           }\n"
"        } else if (stereo_mode == 7) {\n"
"           if ((1.0-gl_TexCoord[0].x) < gl_TexCoord[0].y) {\n"
"               gl_FragColor = vec4(r1, g1, b1, 1.0);\n"
"           } else {\n"
"               gl_FragColor = vec4(r2, g2, b2, 1.0);\n"
"           }\n"
"        } else if (stereo_mode == 8) {\n"
"           if ((gl_FragCoord.y/2.0-float(int(gl_FragCoord.y/2.0))) < 0.5) {\n"
"               gl_FragColor = vec4(r1, g1, b1, 1.0);\n"
"           } else {\n"
"               gl_FragColor = vec4(r2, g2, b2, 1.0);\n"
"           }\n"
"        } else {\n"
"           gl_FragColor = vec4(r1+r2, g1+g2, b1+b2, 1.0);\n"
"        }\n"
"	 }\n"
"}\n";

